# Generated by Django 4.1 on 2022-08-28 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MVT_Familia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='familia',
            name='cumpleaños',
            field=models.DateField(blank=True, null=True),
        ),
    ]
